/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badges: typeof import('./components/Badges.vue')['default']
    BlockQuote: typeof import('./components/BlockQuote.vue')['default']
    Contributors: typeof import('./components/Contributors.vue')['default']
    DatabaseBlock: typeof import('./components/DatabaseBlock.vue')['default']
    DatabaseSelect: typeof import('./components/DatabaseSelect.vue')['default']
    FeaturesList: typeof import('./components/FeaturesList.vue')['default']
    LanguageBlock: typeof import('./components/LanguageBlock.vue')['default']
    LanguageSelect: typeof import('./components/LanguageSelect.vue')['default']
    ListItem: typeof import('./components/ListItem.vue')['default']
    Logo: typeof import('./components/Logo.vue')['default']
    Select: typeof import('./components/Select.vue')['default']
    Tab: typeof import('./components/Tab.vue')['default']
    Tabs: typeof import('./components/Tabs.vue')['default']
    TeamMember: typeof import('./components/TeamMember.vue')['default']
  }
}
